trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # You can use other VM images like 'windows-latest' if preferred

variables:
  javaVersion: '11'  # Specify the Java version you need

steps:
- task: Checkout@1
  inputs:
    clean: true  # Clean checkout of your repository

# Manually Install JDK (Java 11 in this case)
- script: |
    sudo apt-get update
    sudo apt-get install openjdk-11-jdk -y  # Install JDK 11 on Ubuntu-based agents
    java -version  # Check the Java version to verify installation
  displayName: 'Install JDK 11'

- task: Maven@3  # If you're using Maven to build
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-DskipTests'
    goals: 'clean install'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
